package com.example.vk.mvp.model.entity.user

import com.example.vk.mvp.model.entity.photo.CropPhoto
import com.google.gson.annotations.SerializedName

class UserDetail(
    @SerializedName("id") val id: Int,
    @SerializedName("first_name") val firstName: String,
    @SerializedName("last_name") val lastName: String,
    @SerializedName("is_closed") val isClosed: Boolean,
    @SerializedName("can_access_closed") val canAccessClosed: Boolean,
    @SerializedName("sex") val sex: Int,
    @SerializedName("nickname") val nickname: String,
    @SerializedName("domain") val domain: String,
    @SerializedName("screen_name") val screenName: String,
    @SerializedName("bdate") val bdate: String,
    @SerializedName("city") val city: City,
    @SerializedName("country") val country: Country,
    @SerializedName("timezone") val timezone: Int,
    @SerializedName("photo_50") val photo_50: String,
    @SerializedName("photo_100") val photo_100: String,
    @SerializedName("photo_200") val photo_200: String,
    @SerializedName("photo_200_orig") val photo_200_orig: String,
    @SerializedName("photo_max") val photo_max: String,
    @SerializedName("photo_400_orig") val photo_400_orig: String,
    @SerializedName("photo_max_orig") val photo_max_orig: String,
    @SerializedName("photo_id") val photoId: String,
    @SerializedName("has_photo") val hasPhoto: Int,
    @SerializedName("has_mobile") val hasMobile: Int,
    @SerializedName("is_friend") val isFriend: Int,
    @SerializedName("friend_status") val friendStatus: Int,
    @SerializedName("online") val online: Int,
    @SerializedName("can_post") val canPost: Int,
    @SerializedName("can_see_all_posts") val canSeeAllPosts: Int,
    @SerializedName("can_see_audio") val canSeeAudio: Int,
    @SerializedName("can_write_private_message") val canWritePrivateMessage: Int,
    @SerializedName("can_send_friend_request") val canSendFriendRequest: Int,
    @SerializedName("mobile_phone") val mobilePhone: String,
    @SerializedName("home_phone") val homePhone: String,
    @SerializedName("site") val site: String,
    @SerializedName("status") val status: String,
    @SerializedName("last_seen") val lastSeen: LastSeen,
    @SerializedName("crop_photo") val cropPhoto: CropPhoto,
    @SerializedName("verified") val verified: Int,
    @SerializedName("can_be_invited_group") val canBeInvitedGroup: Boolean,
    @SerializedName("followers_count") val followersCount: Int,
    @SerializedName("blacklisted") val blacklisted: Int,
    @SerializedName("blacklisted_by_me") val blacklistedByMe: Int,
    @SerializedName("is_favorite") val is_favorite: Int,
    @SerializedName("is_hidden_from_feed") val isHiddenFromFeed: Int,
    @SerializedName("common_count") val commonCount: Int,
    @SerializedName("occupation") val occupation: Occupation,
    @SerializedName("career") val career: List<Career>,
    @SerializedName("military") val military: List<String>,
    @SerializedName("university") val university: Int,
    @SerializedName("university_name") val universityName: String,
    @SerializedName("faculty") val faculty: Int,
    @SerializedName("faculty_name") val facultyName: String,
    @SerializedName("graduation") val graduation: Int,
    @SerializedName("education_form") val educationForm: String,
    @SerializedName("education_status") val educationStatus: String,
    @SerializedName("home_town") val homeTown: String,
    @SerializedName("relation") val relation: Int,
    @SerializedName("personal") val personal: Personal,
    @SerializedName("interests") val interests: String,
    @SerializedName("music") val music: String,
    @SerializedName("activities") val activities: String,
    @SerializedName("movies") val movies: String,
    @SerializedName("tv") val tv: String,
    @SerializedName("books") val books: String,
    @SerializedName("games") val games: String,
    @SerializedName("universities") val universities: List<Universities>,
    @SerializedName("schools") val schools: List<Schools>,
    @SerializedName("about") val about: String,
    @SerializedName("relatives") val relatives: List<Relatives>,
    @SerializedName("quotes") val quotes: String
)